site_name: Filestructor
site_description: Project structure generator with file content inspection
site_author: Maxim Shushanikov
repo_url: https://github.com/maxshushanikov/filestructor

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          nav:
            - Home: index.md
            - Installation: installation.md
            - Usage: usage.md
            - CLI: cli.md
            - API: api.md
            - Contributing: contributing.md
            - Coverage Report: coverage/index.html
        - locale: ru
          name: Русский
          nav:
            - Главная: index.md
            - Установка: installation.md
            - Использование: usage.md
            - CLI: cli.md
            - API: api.md
            - Вклад: contributing.md
            - Отчёт о покрытии: coverage/index.html
        - locale: de
          name: Deutsch
          nav:
            - Startseite: index.md
            - Installation: installation.md
            - Nutzung: usage.md
            - CLI: cli.md
            - API: api.md
            - Beitrag: contributing.md
            - Testabdeckung: coverage/index.html
