# Configuration for file type exclusion
exclude_file_types:
  # Archive formats
  - .zip
  - .rar
  - .7z
  - .tar
  - .gz
  
  # Binary and executable files
  - .exe
  - .dll
  - .so
  - .bin
  
  # Media files
  - .mp3
  - .mp4
  - .avi
  - .mov
  - .jpg
  - .png
  - .gif
  - .svg
  
  # Document formats
  - .pdf
  - .doc
  - .docx
  - .xlsx
  - .pptx
  
  # System and cache files
  - .log
  - .tmp
  - .cache
  - .DS_Store
  
  # Development artifacts
  - .pyc
  - .class
  - .jar
  - .min.js
  - .min.css

# Optional: exclude directories by pattern
exclude_directories:
  - .git
  - __pycache__
  - .idea
  - venv
  - .venv
  - node_modules
  - .vscode
  - .bin
  - .gradle