name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project and test deps
        run: |
          python -m pip install --upgrade pip
          # Если extras недоступны, можно заменить на: pip install -e . pytest
          pip install -e .[dev]

      - name: Run tests
        run: pytest -q
